version: "3.9"
services:
  db:
    image: postgres:16
    container_name: bt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bt_user
      POSTGRES_PASSWORD: bt_pass
      POSTGRES_DB: bt_db
    ports:
      - "5432:5432"
    volumes:
      - bt_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: bt-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  bt_pgdata: