spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bt_db
    username: bt_user
    password: bt_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      format_sql: true
      jdbc.lob.non_contextual_creation: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080